One smoke test
Automatiserad-testning-och-testverktyg/the-shop pull request #16
Opened 2024-06-11 16:11 UTC by LiBe0413

check title on first page

2024-06-11 16:21 UTC, jamieblomerus requested changes
Du glömde skriva ditt namn i filen och dessutom passerar inte testet lokalt, då webbplatsens titel ändrats idag från `Webbutiken` till `The Shop`.

2024-06-11 16:21 UTC, jamieblomerus commented on src/test/java/com/team2/the_shop/stepDef_SmokeTest.java
>  public class stepDef_SmokeTest {
Du glömde lägga till ditt namn som kommentar på klassen. Se mitt förslag nedan.

```suggestion
public class stepDef_SmokeTest { // Skrivet av Linn Bergström
```

2024-06-11 16:21 UTC, jamieblomerus commented on src/test/java/com/team2/the_shop/stepDef_SmokeTest.java
> +      //  String expectedTitle = "Webbutiken";
Onödig kommentar. Bör tas bort.
```suggestion
```

2024-06-11 16:21 UTC, jamieblomerus commented on src/test/java/com/team2/the_shop/stepDef_SmokeTest.java
> +    public void title_is(String string) {
Det vore bra om `string` byttes ut mot ett mer adekvat namn. Mitt förslag är `expectedTitle`.

```suggestion
    public void title_is(String expectedTitle) {
```

2024-06-11 16:21 UTC, jamieblomerus commented on src/test/java/com/team2/the_shop/stepDef_SmokeTest.java
> +        Assertions.assertEquals(string, actualTitle);
Se tidigare kommentar för information om detta förslag till ändring.

```suggestion
        Assertions.assertEquals(expectedTitle, actualTitle);
```

2024-06-15 16:57 UTC, jamieblomerus requested changes
Din kod är generellt sätt bra skriven, men den har ett antal brister som jag önskar att du åtgärdar innan jag kan godkänna den.

**Vänligen kolla på dessa, genomför de ändringar du anser rimliga och efterfråga en ny granskning så kollar jag igen.**

2024-06-15 16:57 UTC, jamieblomerus commented on src/test/java/com/team2/the_shop/stepDef_homepage.java
> +import org.openqa.selenium.JavascriptExecutor;
Denna import används ej och bör således tas bort.

```suggestion
```

2024-06-15 16:57 UTC, jamieblomerus commented on src/test/java/com/team2/the_shop/stepDef_homepage.java
> +    private By img;
Denna variabel används ej och bör således tas bort.

```suggestion
```

2024-06-15 16:57 UTC, jamieblomerus commented on src/test/java/com/team2/the_shop/stepDef_homepage.java
> +import static org.junit.jupiter.api.Assertions.assertTrue;
Du genomför ej Assertions konsekvent. Vissa utav dem använder `Assertions.assert…` medan `Assertions.assertTrue()` enbart benämns `assertTrue()`.

**Vänligen välj en utav dem och använd den konsekvent.**

2024-06-15 16:57 UTC, jamieblomerus commented on src/test/java/com/team2/the_shop/stepDef_homepage.java
> +        System.out.println(actualTitle);
Det är generellt ansett _[bad practice](https://www.merriam-webster.com/dictionary/bad%20practice)_ att printa ut data i onödan inuti testfall. JUnit kommer automatiskt att printa ut information om testet ej passerar.

**Således föreslår jag att du tar bort denna kodrad.**

```suggestion
```

2024-06-15 16:57 UTC, jamieblomerus commented on src/test/java/com/team2/the_shop/stepDef_homepage.java
> +        System.out.println(newPageTitle);
Det är generellt ansett _[bad practice](https://www.merriam-webster.com/dictionary/bad%20practice)_ att printa ut data i onödan inuti testfall. JUnit kommer automatiskt att printa ut information om testet ej passerar.

**Således föreslår jag att du tar bort denna kodrad.**

```suggestion
```

2024-06-15 16:57 UTC, jamieblomerus commented on src/test/java/com/team2/the_shop/resource/features/HomePage.feature
> +Feature: smoke test
Du verkar glömt att uppdatera feature-namnet när du bytte namn på filen. Vänligen åtgärda detta.

```suggestion
Feature: Home page
```

2024-06-15 16:57 UTC, jamieblomerus commented on .github/workflows/maven.yml
Det är svårt för mig att veta om denna GitHub Workflow fungerar, men om du har testat det och det verkar funka så kör vi på det :)

**Detta är ej en anmärkan på något problem utan enbart en kommentar om att jag ej kunnat testa detta.**

2024-06-15 16:57 UTC, jamieblomerus commented on src/test/java/com/team2/the_shop/TheShopApplicationTests.java
>  import org.junit.jupiter.api.Test;
Denna import används ej längre och bör således tas bort.

```suggestion
```

2024-06-15 16:57 UTC, jamieblomerus commented on src/test/java/com/team2/the_shop/TheShopApplicationTests.java
> +//	}
Generellt anses det vara _[bad practice](https://www.merriam-webster.com/dictionary/bad%20practice)_ att lämna kod utkommenterad. Om vi behöver denna kod igen i framtiden så finns den ju alltid i Git-historiken att kopiera.

**Således föreslår jag att du istället tar bort den.**

```suggestion
```

2024-06-15 16:57 UTC, jamieblomerus commented on src/test/java/com/team2/the_shop/stepDef_homepage.java
> +    }
Jag anser att denna `Given`-sats och funktionsnamn är mycket vilseledande. Det framstår som att detta skulle leda till sidan [Shop](https://webshop-agil-testautomatiserare.netlify.app/products) men den leder egentligen till [startsidan](https://webshop-agil-testautomatiserare.netlify.app).

**Således föreslår jag att du byter ut detta emot följande.**
```java
@Given("User is on the homepage")
public void user_is_on_the_homepage() {
    driver.get("https://webshop-agil-testautomatiserare.netlify.app");
}
```
_**Notera att detta även kräver vissa uppdateringar i feature-filen.**_

2024-06-17 17:41 UTC, LiBe0413 commented on src/test/java/com/team2/the_shop/stepDef_homepage.java
> +import static org.junit.jupiter.api.Assertions.assertTrue;
Changed!

2024-06-17 17:42 UTC, LiBe0413 commented on src/test/java/com/team2/the_shop/stepDef_homepage.java
> +    }
Done!

2024-06-20 22:02 UTC, jamieblomerus approved these changes
**LGTM!**

De brister jag tidigare anmärkt på är nu åtgärdade och koden har en huvudsakligen tillfredställande kvalité. Bra jobbat!

2024-06-23 13:07 UTC, closed without merging

2024-06-23 16:57 UTC, jamieblomerus commented
Ursäkta. Denna PR blev ej inmerge:ad utan du raderade enbart dina ändringar. Vill du att jag återställer det och merge:ar in den i `main` eller var raderandet medvetet?